version: '3.3'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=marihuana

  cliente:
    build: ./cliente/.
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  
  servidor:
    build: ./servidor/.

  redis:
      image: docker.io/bitnami/redis:6.2
      environment:
        # ALLOW_EMPTY_PASSWORD is recommended only for development.
        - ALLOW_EMPTY_PASSWORD=yes
        - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      ports:
        - '6379:6379'
      volumes:
        - 'redis_data:/bitnami/redis/data'
        - './overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf'

volumes:
  redis_data:
    driver: local
  