# syntax=docker/dockerfile:1
FROM ubuntu:20.04
WORKDIR /code
RUN apt-get update
RUN apt-get install python3.7
RUN apt -y install python3-pip
COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 5000
COPY . .
COPY server.py server.py
COPY demo_pb2_grpc.py demo_pb2_grpc.py 
COPY demo_pb2.py demo_pb2.py
CMD python3 server.py